#!/bin/bash

### BEGIN INIT INFO
# Provides:          home-automation
# Required-Start:    $dhcpcd $syslog
# Required-Stop:     $dhcpcd $syslog
# Should-Start:      $portmap
# Should-Stop:       $portmap
# X-Start-Before:    nis
# X-Stop-After:      nis
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

PID_FILE=/tmp/home-automation.pid
HOME_AUTOMATION_PATH=/home/matthew/projects/home-automation

do_start() {
    if [ -f "$PID_FILE" ]; then
        echo "ERROR: PID file exists!" >&2
        exit 1
    fi
    cd "${HOME_AUTOMATION_PATH}"
    python3.5 "home_automation.py" > out.log 2>error.log&
    echo $? > "$PID_FILE"
}

do_stop() {
    if [ ! -f "$PID_FILE" ]; then
        echo "ERROR: Doesn't appear to be running!" >&2
        exit 2
    fi
    kill "$(cat "$PID_FILE")"
    rm -f "$PID_FILE"
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_stop && sleep 5 && do_start
        ;;
esac

exit 0
